# Ort → län. "Norrtlje" och "Falkenberh" är stavfel i TED:s data — de
# mappas som sina rätta orter i stället för att tappas.
# Ort → län. Orterna är kommunsäten, så tilldelningen är entydig.
LAN = {
"AB":("Stockholm",["Stockholm","Solna","Tumba","Huddinge","Haninge","Sundbyberg","Sollentuna",
 "Märsta","Tyresö","Nacka","Täby","Lidingö","Djursholm","Norrtälje","Gustavsberg","Järfälla",
 "Åkersberga","Ekerö","Nynäs","Vallentuna","Upplands Väsby","Danderyd","Bromma","Kista",
 "Vaxholm","Nynäshamn","Kungsängen","Nykvarn","Hässelby","Norrtlje","Sigtuna","Rönninge","Segeltorp","Skärholmen","Farsta","Älvsjö","Hägersten"]),
"C":("Uppsala",["Uppsala","Tierp","Enköping","Östhammar","Bålsta","Knivsta","Alunda","Heby","Gimo","Skutskär"]),
"D":("Södermanland",["Nyköping","Eskilstuna","Strängnäs","Katrineholm","Flen","Gnesta","Trosa","Oxelösund","Vingåker","Malmköping"]),
"E":("Östergötland",["Linköping","Norrköping","Motala","Mjölby","Finspång","Valdemarsvik","Åtvidaberg",
 "Söderköping","Vadstena","Kisa","Skänninge","Boxholm","Ödeshög"]),
"F":("Jönköping",["Jönköping","Värnamo","Nässjö","Vetlanda","Tranås","Gislaved","Skillingaryd","Eksjö",
 "Sävsjö","Aneby","Habo","Mullsjö","Gnosjö","Vaggeryd","Bodafors"]),
"G":("Kronoberg",["Växjö","Ljungby","Alvesta","Älmhult","Tingsryd","Lessebo","Markaryd","Åseda","Lenhovda"]),
"H":("Kalmar",["Kalmar","Västervik","Oskarshamn","Hultsfred","Mönsterås","Nybro","Vimmerby","Emmaboda",
 "Borgholm","Färjestaden","Torsås","Mörbylånga","Högsby"]),
"I":("Gotland",["Visby","Hemse","Slite"]),
"K":("Blekinge",["Karlskrona","Karlshamn","Ronneby","Sölvesborg","Olofström"]),
"M":("Skåne",["Malmö","Lund","Helsingborg","Kristianstad","Hässleholm","Trelleborg","Landskrona",
 "Ängelholm","Ystad","Lomma","Eslöv","Båstad","Svedala","Sjöbo","Simrishamn","Höganäs","Arlöv",
 "Vellinge","Svalöv","Skurup","Kävlinge","Broby","Staffanstorp","Bjuv","Åstorp","Klippan","Perstorp",
 "Osby","Bromölla","Tomelilla","Höör","Hörby","Löddeköpinge","Bara","Limhamn","Genarp","Veberöd","Dalby","Åhus"]),
"N":("Halland",["Halmstad","Kungsbacka","Varberg","Falkenberg","Laholm","Hyltebruk","Getinge","Oskarström","Falkenberh"]),
"O":("Västra Götaland",["Göteborg","Vänersborg","Borås","Trollhättan","Uddevalla","Lerum","Mölndal",
 "Lidköping","Skövde","Ulricehamn","Kungälv","Alingsås","Falköping","Strömstad","Vårgårda","Kinna",
 "Alafors","Stenungsund","Mölnlycke","Mellerud","Henån","Bollebygd","Partille","Åmål","Mariestad",
 "Skara","Tidaholm","Vara","Tibro","Töreboda","Herrljunga","Svenljunga","Tranemo","Lysekil","Munkedal",
 "Tanum","Färgelanda","Sotenäs","Orust","Ale","Öckerö","Tjörn","Grästorp","Essunga","Karlsborg","Gullspång","Hjo","Götene","Bengtsfors","Dals-Ed","Lilla Edet","Floda","Sävedalen","Nödinge","Kungshamn","Hisings Backa","Västra Frölunda","Askim","Torslanda","Billdal","Tanumshede","Ed","Angered","Nossebro","Skärhamn"]),
"S":("Värmland",["Karlstad","Kristinehamn","Arvika","Säffle","Sunne","Torsby","Forshaga","Filipstad",
 "Hagfors","Storfors","Munkfors","Grums","Kil","Årjäng","Eda","Charlottenberg","Skoghall","Hammarö"]),
"T":("Örebro",["Örebro","Kumla","Karlskoga","Hallsberg","Lindesberg","Nora","Askersund","Degerfors",
 "Fjugesta","Laxå","Hällefors","Ljusnarsberg","Kopparberg","Odensbacken"]),
"U":("Västmanland",["Västerås","Köping","Sala","Fagersta","Arboga","Hallstahammar","Surahammar",
 "Skinnskatteberg","Norberg","Kungsör"]),
"W":("Dalarna",["Falun","Ludvika","Borlänge","Mora","Avesta","Hedemora","Leksand","Rättvik","Säter",
 "Smedjebacken","Malung","Vansbro","Orsa","Älvdalen","Gagnef","Djurås","Insjön"]),
"X":("Gävleborg",["Gävle","Söderhamn","Sandviken","Ljusdal","Bollnäs","Hudiksvall","Ockelbo","Hofors","Edsbyn","Järvsö"]),
"Y":("Västernorrland",["Sundsvall","Örnsköldsvik","Härnösand","Kramfors","Timrå","Sollefteå","Ånge","Matfors"]),
"Z":("Jämtland",["Östersund","Åre","Strömsund","Sveg","Järpen","Bräcke","Krokom","Hammarstrand","Gäddede","Föllinge"]),
"AC":("Västerbotten",["Umeå","Skellefteå","Lycksele","Vilhelmina","Storuman","Vindeln","Robertsfors",
 "Nordmaling","Bjurholm","Malå","Norsjö","Sorsele","Dorotea","Åsele","Vännäs","Holmsund"]),
"BD":("Norrbotten",["Luleå","Boden","Piteå","Kiruna","Gällivare","Kalix","Haparanda","Älvsbyn",
 "Arvidsjaur","Jokkmokk","Pajala","Överkalix","Övertorneå","Arjeplog","Malmberget","Koskullskulle"]),
}
CITY2LAN = {c: k for k,(_,cs) in LAN.items() for c in cs}
# schematisk rutkarta — ungefärligt geografiskt läge, inga påhittade gränser
GRID = {"BD":(4,0),"AC":(3,1),"Z":(2,2),"Y":(3,2),"W":(2,3),"X":(3,3),
        "S":(1,4),"T":(2,4),"U":(3,4),"C":(4,4),
        "O":(1,5),"E":(2,5),"D":(3,5),"AB":(4,5),
        "N":(1,6),"F":(2,6),"H":(3,6),"I":(4,6),
        "G":(2,7),"K":(3,7),"M":(2,8)}
